# Análise dos dados do SIM

In [271]:
import pandas as pd

## Importação dos dados que serão utilizados

In [272]:
caminho_dados_es = '/content/drive/MyDrive/dados/Projeto Integrador VI/DOES2020.csv'
caminho_dados_mg = '/content/drive/MyDrive/dados/Projeto Integrador VI/DOMG2020.csv'
caminho_dados_rj = '/content/drive/MyDrive/dados/Projeto Integrador VI/DORJ2020.csv'
caminho_dados_sp = '/content/drive/MyDrive/dados/Projeto Integrador VI/DOSP2020.csv'
caminho_cadmun = '/content/drive/MyDrive/dados/Projeto Integrador VI/CADMUN.csv'
caminho_relacao_pais = '/content/drive/MyDrive/dados/Projeto Integrador VI/relacao_pais.csv'
caminho_relacao_estado = '/content/drive/MyDrive/dados/Projeto Integrador VI/relacao_estado.csv'
caminho_escolaridade = '/content/drive/MyDrive/dados/Projeto Integrador VI/escolaridade.csv'
caminho_cid = '/content/drive/MyDrive/dados/Projeto Integrador VI/CID10.csv'

## Criação dos dataframes

In [273]:
df_es = pd.read_csv(caminho_dados_es, dtype={'DTOBITO': str, 'NATURAL': str, 'CODMUNNATU': str, 'DTNASC':str, 'SEXO': str, 'RACACOR': str, 'CODMUNRES': str, 'ASSISTMED': str, 'LINHAA': str, 'ESCFALAGR1': str})
df_mg = pd.read_csv(caminho_dados_mg, dtype={'DTOBITO': str, 'NATURAL': str, 'CODMUNNATU': str, 'DTNASC':str, 'SEXO': str, 'RACACOR': str, 'CODMUNRES': str, 'ASSISTMED': str, 'LINHAA': str, 'ESCFALAGR1': str})
df_rj = pd.read_csv(caminho_dados_rj, dtype={'DTOBITO': str, 'NATURAL': str, 'CODMUNNATU': str, 'DTNASC':str, 'SEXO': str, 'RACACOR': str, 'CODMUNRES': str, 'ASSISTMED': str, 'LINHAA': str, 'ESCFALAGR1': str})
df_sp = pd.read_csv(caminho_dados_sp, dtype={'DTOBITO': str, 'NATURAL': str, 'CODMUNNATU': str, 'DTNASC':str, 'SEXO': str, 'RACACOR': str, 'CODMUNRES': str, 'ASSISTMED': str, 'LINHAA': str, 'ESCFALAGR1': str})
df_municipios = pd.read_csv(caminho_cadmun, encoding ='cp1250', dtype={'MUNCOD':str,'MUNCODDV':str})
df_pais = pd.read_csv(caminho_relacao_pais, dtype={'id': str, 'nome': str})
df_estado = pd.read_csv(caminho_relacao_estado, dtype={'id': str, 'nome': str})
df_escolaridade = pd.read_csv(caminho_escolaridade, dtype={'codigo':str})
df_causa_morte = pd.read_csv(caminho_cid, encoding ='cp1250')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (79) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (66,79) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Inserindo uma nova coluna que identifica de qual dataframe esse dado é originado

In [274]:
if 'DF_ORIGEM' not in  df_es:
  df_es.insert(0,'DF_ORIGEM','ES')
if 'DF_ORIGEM' not in  df_mg:
  df_mg.insert(0,'DF_ORIGEM','MG')
if 'DF_ORIGEM' not in  df_rj:
  df_rj.insert(0,'DF_ORIGEM','RJ')
if 'DF_ORIGEM' not in  df_sp:
  df_sp.insert(0,'DF_ORIGEM','SP')

## Tratamento dos dados

### Tratar colunas DTOBITO e DTNASC como datas

In [275]:
df_es['DTOBITO'] = pd.to_datetime(df_es['DTOBITO'], format = '%d%m%Y')
df_es['DTNASC'] = pd.to_datetime(df_es['DTNASC'], format = '%d%m%Y')
df_es.rename(columns={'DTOBITO': 'Data de Obito'}, inplace = True)
df_es.rename(columns={'DTNASC': 'Data de Nascimento'}, inplace = True)
df_es

      DF_ORIGEM  ORIGEM  TIPOBITO  ... FONTESINF  ALTCAUSA CONTADOR
0            ES       1         2  ...       NaN       NaN      431
1            ES       1         2  ...       NaN       NaN      432
2            ES       1         2  ...       NaN       NaN      433
3            ES       1         2  ...       NaN       NaN      434
4            ES       1         2  ...       NaN       NaN      435
...         ...     ...       ...  ...       ...       ...      ...
29023        ES       1         2  ...       NaN       NaN  1549956
29024        ES       1         2  ...       NaN       NaN  1549972
29025        ES       1         2  ...       NaN       NaN  1550142
29026        ES       2         2  ...       NaN       NaN  1550759
29027        ES       2         2  ...       NaN       NaN  1550760

[29028 rows x 88 columns]

In [276]:
df_mg['DTOBITO'] = pd.to_datetime(df_mg['DTOBITO'], format = '%d%m%Y')
df_mg['DTNASC'] = pd.to_datetime(df_mg['DTNASC'], format = '%d%m%Y')
df_mg.rename(columns={'DTOBITO': 'Data de Obito'}, inplace = True)
df_mg.rename(columns={'DTNASC': 'Data de Nascimento'}, inplace = True)
df_mg

       DF_ORIGEM  ORIGEM  TIPOBITO  ... FONTESINF  ALTCAUSA CONTADOR
0             MG       1         2  ...       NaN       NaN        1
1             MG       1         2  ...       NaN       NaN        2
2             MG       1         2  ...       NaN       NaN        3
3             MG       1         2  ...       NaN       NaN        4
4             MG       1         2  ...       NaN       NaN        5
...          ...     ...       ...  ...       ...       ...      ...
151364        MG       1         2  ...       NaN       NaN  1550114
151365        MG       1         2  ...       NaN       NaN  1550115
151366        MG       1         2  ...       NaN       NaN  1550137
151367        MG       1         2  ...       NaN       NaN  1550138
151368        MG       2         2  ...       NaN       NaN  1550767

[151369 rows x 88 columns]

In [277]:
df_rj['DTOBITO'] = pd.to_datetime(df_rj['DTOBITO'], format = '%d%m%Y')
df_rj['DTNASC'] = pd.to_datetime(df_rj['DTNASC'], format = '%d%m%Y')
df_rj.rename(columns={'DTOBITO': 'Data de Obito'}, inplace = True)
df_rj.rename(columns={'DTNASC': 'Data de Nascimento'}, inplace = True)
df_rj

       DF_ORIGEM  ORIGEM  TIPOBITO  ... FONTESINF  ALTCAUSA CONTADOR
0             RJ       1         2  ...       NaN       NaN      457
1             RJ       1         2  ...       NaN       NaN      458
2             RJ       1         2  ...       NaN       NaN      459
3             RJ       1         2  ...       NaN       NaN      460
4             RJ       1         2  ...       NaN       NaN      461
...          ...     ...       ...  ...       ...       ...      ...
171462        RJ       2         2  ...       NaN       NaN  1551745
171463        RJ       2         2  ...       NaN       NaN  1551746
171464        RJ       2         2  ...       NaN       NaN  1551747
171465        RJ       2         2  ...       NaN       NaN  1551748
171466        RJ       2         2  ...       NaN       NaN  1551749

[171467 rows x 88 columns]

In [278]:
df_sp['DTOBITO'] = pd.to_datetime(df_sp['DTOBITO'], format = '%d%m%Y')
df_sp['DTNASC'] = pd.to_datetime(df_sp['DTNASC'], format = '%d%m%Y')
df_sp.rename(columns={'DTOBITO': 'Data de Obito'}, inplace = True)
df_sp.rename(columns={'DTNASC': 'Data de Nascimento'}, inplace = True)
df_sp

       DF_ORIGEM  ORIGEM  TIPOBITO  ... FONTESINF  ALTCAUSA CONTADOR
0             SP       1         2  ...       NaN       NaN       26
1             SP       1         2  ...       NaN       NaN       27
2             SP       1         2  ...       NaN       2.0       28
3             SP       1         2  ...       NaN       NaN       29
4             SP       1         2  ...       NaN       NaN       30
...          ...     ...       ...  ...       ...       ...      ...
349154        SP       2         2  ...       NaN       NaN  1552596
349155        SP       2         2  ...       NaN       NaN  1552597
349156        SP       2         2  ...       NaN       NaN  1552598
349157        SP       2         2  ...       NaN       NaN  1552599
349158        SP       2         2  ...       NaN       NaN  1552600

[349159 rows x 88 columns]

### Concatenando todas as bases

In [279]:
df_concatenado = pd.concat([df_es, df_mg, df_rj, df_sp])
df_concatenado

       DF_ORIGEM  ORIGEM  TIPOBITO  ... FONTESINF  ALTCAUSA CONTADOR
0             ES       1         2  ...       NaN       NaN      431
1             ES       1         2  ...       NaN       NaN      432
2             ES       1         2  ...       NaN       NaN      433
3             ES       1         2  ...       NaN       NaN      434
4             ES       1         2  ...       NaN       NaN      435
...          ...     ...       ...  ...       ...       ...      ...
349154        SP       2         2  ...       NaN       NaN  1552596
349155        SP       2         2  ...       NaN       NaN  1552597
349156        SP       2         2  ...       NaN       NaN  1552598
349157        SP       2         2  ...       NaN       NaN  1552599
349158        SP       2         2  ...       NaN       NaN  1552600

[701023 rows x 88 columns]

### Selecionando somente as colunas com dados importantes para a nossa analise

In [280]:
df_colunas_selecionadas = df_concatenado[['DF_ORIGEM', 'Data de Obito', 'NATURAL', 'CODMUNNATU', 'Data de Nascimento', 'SEXO', 'RACACOR', 'CODMUNRES', 'ASSISTMED', 'LINHAA', 'ESCFALAGR1']]
df_colunas_selecionadas

       DF_ORIGEM Data de Obito NATURAL  ... ASSISTMED      LINHAA ESCFALAGR1
0             ES    2020-05-08     832  ...         1       *K550        NaN
1             ES    2020-05-08     832  ...         2       *Y000         08
2             ES    2020-05-12     800  ...         1       *G932         09
3             ES    2020-03-07     832  ...         1       *I639         09
4             ES    2020-03-11     831  ...         1       *I679         11
...          ...           ...     ...  ...       ...         ...        ...
349154        SP    2020-06-22     829  ...       NaN  *J988*U049         09
349155        SP    2020-04-23     831  ...         1       *J969         10
349156        SP    2020-06-23     831  ...         1  *J988*U049         10
349157        SP    2020-06-23     825  ...         1  *J988*U049         10
349158        SP    2020-06-24     835  ...         1  *J988*U049         10

[701023 rows x 11 columns]

In [281]:
df_municipios = df_municipios[['MUNCOD','MUNNOME']]
df_municipios

      MUNCOD                      MUNNOME
0     000000         Ignorado ou exterior
1     110000      Município ignorado - RO
2     110001        Alta Floresta D'Oeste
3     110002                    Ariquemes
4     110003                       Cabixi
...      ...                          ...
5647  522208  Wanderlândia (transf. p/TO)
5648  522210       Xambioá (transf. p/TO)
5649  522220                     Vila Boa
5650  522230                Vila Propício
5651  530010                     Brasília

[5652 rows x 2 columns]

### Pegando o nome do Municipio de Naturalidade

In [282]:
df_colunas_selecionadas = df_colunas_selecionadas.merge(df_municipios,how='left', left_on='CODMUNNATU', right_on='MUNCOD')
df_colunas_selecionadas = df_colunas_selecionadas[['DF_ORIGEM','Data de Obito', 'NATURAL', 'Data de Nascimento', 'SEXO', 'RACACOR', 'CODMUNRES', 'ASSISTMED', 'LINHAA', 'ESCFALAGR1','MUNNOME']]
df_colunas_selecionadas.rename(columns={'MUNNOME': 'Municipio Natural'}, inplace = True)
df_colunas_selecionadas

       DF_ORIGEM Data de Obito  ... ESCFALAGR1  Municipio Natural
0             ES    2020-05-08  ...        NaN     Afonso Cláudio
1             ES    2020-05-08  ...         08         Vila Velha
2             ES    2020-05-12  ...         09                NaN
3             ES    2020-03-07  ...         09       Baixo Guandu
4             ES    2020-03-11  ...         11   Conselheiro Pena
...          ...           ...  ...        ...                ...
701018        SP    2020-06-22  ...         09         Barro Alto
701019        SP    2020-04-23  ...         10             Lavras
701020        SP    2020-06-23  ...         10  Brasília de Minas
701021        SP    2020-06-23  ...         10         Mamanguape
701022        SP    2020-06-24  ...         10          Mairiporă

[701023 rows x 11 columns]

### Pegando o nome do Municipio de residência

In [283]:
df_colunas_selecionadas = df_colunas_selecionadas.merge(df_municipios,how='left', left_on='CODMUNRES', right_on='MUNCOD')
df_colunas_selecionadas = df_colunas_selecionadas[['DF_ORIGEM','Data de Obito', 'NATURAL', 'Data de Nascimento', 'SEXO', 'RACACOR', 'ASSISTMED', 'LINHAA', 'ESCFALAGR1', 'Municipio Natural','MUNNOME']]
df_colunas_selecionadas.rename(columns={'MUNNOME': 'Municipio Residência'}, inplace = True)
df_colunas_selecionadas

       DF_ORIGEM Data de Obito  ...  Municipio Natural Municipio Residência
0             ES    2020-05-08  ...     Afonso Cláudio            Cariacica
1             ES    2020-05-08  ...         Vila Velha              Vitória
2             ES    2020-05-12  ...                NaN           Vila Velha
3             ES    2020-03-07  ...       Baixo Guandu           Vila Velha
4             ES    2020-03-11  ...   Conselheiro Pena                Serra
...          ...           ...  ...                ...                  ...
701018        SP    2020-06-22  ...         Barro Alto            Săo Paulo
701019        SP    2020-04-23  ...             Lavras            Săo Paulo
701020        SP    2020-06-23  ...  Brasília de Minas            Săo Paulo
701021        SP    2020-06-23  ...         Mamanguape            Săo Paulo
701022        SP    2020-06-24  ...          Mairiporă            Săo Paulo

[701023 rows x 11 columns]

### Tratar coluna NATURAL

Transforma a coluna 'id' do dataframe df_pais no index

In [284]:
df_pais.set_index('id', inplace = True)

Cria um dicionário tendo como referência o dataframa df_pais

In [285]:
dict_pais = df_pais.to_dict()
dict_pais = dict_pais.get('nome')
dict_pais

{'100': 'ESCÓCIA',
 '101': 'ILHAS FAROES',
 '102': 'FINLÂNDIA',
 '103': 'GIBRALTAR',
 '104': 'GRÉCIA',
 '105': 'HOLANDA',
 '106': 'HUNGRIA',
 '107': 'ILHAS BALEARES',
 '108': 'ILHAS COSMOLEDO (LOMORES)',
 '109': 'ILHAS DO CANAL',
 '110': 'INGLATERRA',
 '111': 'IRLANDA DO NORTE',
 '112': 'IRLANDA',
 '113': 'ISLÂNDIA',
 '114': 'IUGOSLÁVIA',
 '115': 'LIECHTENSTEIN',
 '116': 'LUXEMBURGO',
 '117': 'ILHAS DE MAN',
 '118': ' MÔNACO',
 '119': 'NORUEGA',
 '120': 'REPÚBLICA DE MALTA',
 '121': 'PAÍS DE GALES',
 '122': 'PAÍSES BAIXOS',
 '123': 'POLÔNIA',
 '124': 'ROMÊNIA',
 '125': 'SAN MARINO',
 '126': 'SUÉCIA',
 '127': 'SVALBARD E JAN MAYER,IS',
 '128': 'TCHECOSLOVÁQUIA',
 '129': 'ESTADO DA CIDADE DO VATICANO',
 '130': 'CROÁCIA',
 '131': 'SÉRVIA',
 '132': 'ESLOVÊNIA',
 '133': 'REPÚBLICA DA MACEDÔNIA',
 '134': 'BÓSNIA HERZEGOVINA',
 '135': 'REPÚBLICA TCHECA',
 '136': 'ESLOVÁQUIA',
 '137': 'MONTENEGRO',
 '138': 'AZERBAIJÃO',
 '139': 'BASHKISTA',
 '140': 'REPÚBLICA DA BIELORRÚSSIA',
 '141': 'BURYAT',
 '142': 'CARÉLIA',
 '143': 'CAZAQUISTÃO',
 '144': 'CHECHEN INGUSTH',
 '145': 'CHUVASH',
 '146': 'DAGESTA',
 '147': 'ESTÔNIA',
 '148': 'GEÓRGIA',
 '149': 'GORNO ALTAI',
 '150': 'KABARDINO BALKAR',
 '151': 'KALMIR',
 '152': 'KARACHAEVOCHERKESS',
 '153': 'KHAKASS',
 '154': 'KOMI',
 '155': 'LETÔNIA',
 '156': 'LITUÂNIA',
 '157': 'MARI',
 '158': 'MOLDÁVIA',
 '159': 'OSSETIA SETENTRIONAL',
 '160': 'QUIRGUISTÃO',
 '161': 'TADJIQUISTÃO',
 '162': 'TARTARIA',
 '163': 'TURCOMENISTÃO',
 '164': 'TUVIN',
 '165': 'UCRÂNIA',
 '166': 'UDMURT',
 '167': 'UNIÃO SOVIÉTICA',
 '168': 'UZBEQUISTÃO',
 '169': 'YAKUT',
 '17': 'NOVA ZELÂNDIA',
 '170': 'ABISSÍNIA',
 '171': 'AÇORES',
 '172': 'AFAR FRANCÊS',
 '173': 'REPÚBLICA DA ÁFRICA DO SUL',
 '174': 'ALTO VOLTA',
 '175': 'ANGOLA',
 '176': 'ARGÉLIA',
 '177': 'BECHUANALÂNDIA',
 '178': 'BENIN',
 '179': 'BOTSUANA',
 '180': 'BURUNDI',
 '181': 'CAMARÕES',
 '182': 'CEUTA E MELILLA',
 '183': 'CHADE',
 '184': 'ILHAS COMORES',
 '185': 'CONGO',
 '186': 'COSTA DO MARFIM',
 '187': 'DAOMÉ',
 '188': 'DJIBUTI',
 '189': 'REPÚBLICA ÁRABE DO EGITO',
 '190': 'ETIÓPIA',
 '191': 'REPÚBLICA DO GABÃO',
 '192': 'GÂMBIA',
 '193': 'GANA',
 '194': 'GAZA',
 '195': 'GUINÉ',
 '196': 'GUINÉ EQUATORIAL',
 '197': 'IFNI',
 '198': 'ASCENSÃO E TRISTÃO DA CUNHA, IS',
 '199': 'ILHAS CANÁRIAS',
 '20': 'RESERVADO',
 '200': 'LESOTO',
 '201': 'LIBÉRIA',
 '202': 'LÍBIA',
 '203': 'MADEIRA',
 '204': 'MALAWI',
 '205': 'MADAGASCAR',
 '206': 'MALI',
 '207': 'MARROCOS',
 '208': 'MAURÍCIO',
 '209': 'MAURITÂNIA',
 '21': 'ARGENTINA',
 '210': 'MOÇAMBIQUE',
 '211': 'NGUANE',
 '212': 'REPÚBLICA DO NÍGER',
 '213': 'NIGÉRIA',
 '214': 'PAPUA NOVA GUINÉ',
 '215': 'PRAÇAS NORTE AFRICANAS',
 '216': 'PROTETOR DO SUDOESTE AFRICANO',
 '217': 'QUÊNIA',
 '218': 'REPÚBLICA CENTRO AFRICANA',
 '219': 'REUNIÃO',
 '22': 'BOLÍVIA',
 '220': 'RODÉSIA (ZIMBÁBWE)',
 '221': 'RUANDA',
 '222': 'SAARA ESPANHOL',
 '223': 'SANTA HELENA',
 '224': 'SÃO TOMÉ E PRÍNCIPE',
 '225': 'SEYCHELLES',
 '226': 'SERRA LEOA',
 '227': 'SOMÁLIA, REPÚBLICA',
 '228': 'SUAZILÂNDIA',
 '229': 'SUDÃO',
 '23': 'CHILE',
 '230': 'TANGANICA',
 '231': 'TERRIT. BRITÂNICO DO OCEANO INDICO',
 '232': 'TRANSKEI',
 '233': 'TOGO',
 '234': 'TUNÍSIA',
 '235': 'UGANDA',
 '236': 'ZAIRE',
 '237': 'ZÂMBIA',
 '238': 'BURKINA FASSO',
 '239': 'ZIMBÁBWE',
 '24': 'PARAGUAI',
 '240': 'NAMÍBIA',
 '241': 'AFEGANISTÃO',
 '242': 'ARÁBIA SAUDITA',
 '243': 'BAHREIN',
 '244': 'BIRMÂNIA',
 '245': 'BRUNEI',
 '246': 'BHUTAN',
 '247': 'CATAR',
 '248': 'CEILÃO',
 '249': 'CHINA (TAIWAN)',
 '25': 'URUGUAI',
 '250': 'COVEITE',
 '251': 'EMIRADOS ÁRABES UNIDOS',
 '252': 'FILIPINAS',
 '253': 'HONG-KONG',
 '254': 'IEMEN',
 '255': 'ÍNDIA',
 '256': 'INDONÉSIA',
 '257': 'IRÃ',
 '258': 'IRAQUE',
 '259': 'ISRAEL',
 '26': 'COLÔMBIA',
 '260': 'JORDÂNIA',
 '261': 'KMER/CAMBOJA',
 '262': 'KUWAIT',
 '263': 'LAOS',
 '264': 'LÍBANO',
 '265': 'MACAU',
 '266': 'MALÁSIA',
 '267': 'MALDIVAS,IS',
 '268': 'MASCATE',
 '269': 'MONGÓLIA',
 '27': 'EQUADOR',
 '270': 'NEPAL',
 '271': 'OMAN',
 '272': 'PALESTINA',
 '273': 'PAQUISTÃO',
 '274': 'RUIQUIU,IS',
 '275': 'CINGAPURA',
 '276': 'SEQUIN',
 '277': 'SÍRIA',
 '278': 'SRI-LANKA',
 '279': 'TAILÂNDIA',
 '28': 'ANTÍGUA E. DEP. BARBUDA',
 '280': 'TRÉGUA, ESTADO',
 '281': 'TURQUIA',
 '282': 'VIETNÃ DO NORTE',
 '283': 'VIETNÃ DO SUL',
 '284': 'MIANMA',
 '285': 'ARQUIPÉLAGO MANAHIKI',
 '286': 'ARQUIPÉLAGO MIDWAY',
 '287': 'ASHMORE E CARTIER',
 '288': 'AUSTRÁLIA',
 '289': 'ARQUIPÉLAGO DE BISMARK',
 '29': 'ANTILHAS HOLANDESAS',
 '290': 'ILHAS COOK',
 '291': 'REPÚBLICA DE FIJI',
 '292': 'GUAM',
 '293': 'ILHAS BAKER',
 '294': 'ILHAS CANTÃO E ENDERBURG',
 '295': 'ILHAS CAROLINAS',
 '296': 'ILHAS DO PACÍFICO',
 '297': 'ILHAS CHRISTMAS',
 '298': 'ILHAS GILBERT',
 '299': 'ILHAS HOWLAND E JARVIS',
 '30': 'ALEMANHA',
 '300': 'ILHA JOHNSTON E SAND',
 '301': 'ILHAS KINGMAN REEF',
 '302': 'ILHAS MACQUAIRE',
 '303': 'ILHAS MARIANAS',
 '304': 'ILHAS MARSHALL',
 '305': 'ILHAS MACDONAL E HEARD',
 '306': 'ILHAS NIUE',
 '307': 'ILHAS NORFOLK',
 '308': 'ILHAS PALAU',
 '309': 'ILHAS SALOMÃO',
 '31': 'BÉLGICA',
 '310': 'ILHAS TOKELAU',
 '311': 'ILHAS WAKE',
 '312': 'KALIMATAN',
 '313': 'ILHAS LINHA',
 '314': 'NAURU',
 '315': 'ILHAS NOVA CALEDÔNIA',
 '316': 'NOVA GUINÉ',
 '318': 'ILHAS NOVAS HEBRIDAS',
 '319': 'TERRITÓRIO DE PAPUA',
 '32': 'GRÃ-BRETANHA',
 '320': 'ILHAS PÁSCOA',
 '321': 'ILHAS PITCAIRIN',
 '322': 'POLINÉSIA FRANCESA',
 '323': 'SABAH',
 '324': 'SAMOA AMERICANA',
 '325': 'SAMOA OCIDENTAL',
 '326': 'ILHAS SANTA CRUZ',
 '327': 'SARAWAK',
 '328': 'TERRITÓRIO DE COCO',
 '329': 'TIMOR',
 '33': 'ARUBA',
 '330': 'TONGA',
 '331': 'TUVALU',
 '332': 'ILHAS WALLIS E FUTUNA',
 '333': 'ANTÁRTICO BRITÂNICO, TERRITORIO',
 '334': 'ANTÁRTICA FRANCESA',
 '335': 'TERR. ANTÁRTICO DA AUSTRÁLIA',
 '336': 'ANTÁRTICO CHILENO',
 '337': 'ANTÁRTICO ARGENTINO',
 '338': 'ANTÁRTICO NORUEGUES',
 '339': 'APÁTRIDA',
 '34': 'CANADÁ',
 '340': 'DEPENDÊNCIA DE ROSS',
 '341': 'TERRAS AUSTRAIS',
 '342': 'BANGLADESH',
 '343': 'CABO VERDE',
 '344': 'GUINÉ BISSAU',
 '345': 'IEMEN DO SUL',
 '346': 'KARA KALPAK',
 '347': 'ARMÊNIA',
 '348': 'RÚSSIA',
 '349': 'SENEGAL',
 '35': 'ESPANHA',
 '350': 'TANZÂNIA',
 '36': 'ESTADOS UNIDOS DA AMÉRICA (EUA)',
 '37': 'FRANÇA',
 '38': 'SUÍÇA',
 '39': 'ITÁLIA',
 '40': 'COMUNIDADE DAS BAHAMAS',
 '41': 'JAPÃO',
 '42': 'CHINA',
 '43': 'CORÉIA',
 '44': 'BARBADOS',
 '45': 'PORTUGAL',
 '46': 'BELIZE',
 '47': 'ILHAS TURKS E CAICOS',
 '48': 'RESERVADO',
 '49': 'RESERVADO',
 '50': 'RESERVADO',
 '51': 'COSTA RICA',
 '52': 'CUBA',
 '53': 'CURAÇAO',
 '54': 'COMUNIDADE DOMINICANA',
 '55': 'REPÚBLICA DOMINICANA',
 '56': 'REPÚBLICA DE EL SALVADOR',
 '57': 'ESTADOS ASSOC. DAS ANTILHAS',
 '58': 'ILHAS FALKLANDS',
 '59': 'GRANADA',
 '60': 'ILHAS GUADALUPE',
 '61': 'GUATEMALA',
 '62': 'REPÚBLICA DO HAITI',
 '63': 'HONDURAS BRITÂNICAS',
 '64': 'HONDURAS',
 '65': 'ILHAS SERRANAS',
 '66': 'JAMAICA',
 '67': 'ILHAS MALVINAS',
 '68': 'MARTINICA',
 '69': 'ILHA MILHOS',
 '70': 'MONTE SERRAT',
 '71': 'NICARÁGUA',
 '72': 'PANAMÁ',
 '73': 'PANAMÁ – ZONA DO CANAL',
 '74': 'PORTO RICO',
 '75': 'QUITASUENO',
 '76': 'RONCADOR',
 '77': 'SANTA LÚCIA',
 '78': 'SÃO CRISTÓVÃO',
 '79': 'SÃO VICENTE',
 '8': 'BRASIL',
 '80': 'ILHAS TURCA',
 '81': 'ILHAS VIRGENS BRITÂNICAS',
 '82': 'ILHAS VIRGENS AMERICANAS',
 '83': 'BERMUDAS',
 '84': 'GROENLÂNDIA',
 '85': 'MÉXICO',
 '86': 'ST. PIERRE ET MIQUELON',
 '87': 'GUIANA FRANCESA',
 '88': 'REPÚBLICA GUIANA',
 '89': 'PERU',
 '90': 'SURINAME',
 '91': 'TRINIDAD E TOBAGO',
 '92': 'VENEZUELA',
 '93': 'ALBÂNIA',
 '94': 'ANDORRA',
 '95': 'ÁUSTRIA',
 '96': 'BULGÁRIA',
 '97': 'CHIPRE',
 '98': 'DINAMARCA',
 '99': 'EIRE'}

Transforma a coluna 'id' do dataframe df_estado no index

In [286]:
df_estado.set_index('id', inplace = True)

Cria um dicionário tendo como referência o dataframe df_estado

In [287]:
dict_estado = df_estado.to_dict()
dict_estado = dict_estado.get('nome')
dict_estado

{'11': 'Rondônia',
 '12': 'Acre',
 '13': 'Amazonas',
 '14': 'Roraima',
 '15': 'Pará',
 '16': 'Amapá',
 '17': 'Tocantins',
 '21': 'Maranhão',
 '22': 'Piauí',
 '23': 'Ceará',
 '24': 'Rio Grande do Norte',
 '25': 'Paraíba',
 '26': 'Pernambuco',
 '27': 'Alagoas',
 '28': 'Sergipe',
 '29': 'Bahia',
 '31': 'Minas Gerais',
 '32': 'Espírito Santo',
 '33': 'Rio de Janeiro',
 '35': 'São Paulo',
 '41': 'Paraná',
 '42': 'Santa Catarina',
 '43': 'Rio Grande do Sul',
 '50': 'Mato Grosso do Sul',
 '51': 'Mato Grosso',
 '52': 'Goiás',
 '53': 'Distrito Federal'}

Cria as duas colunas que receberão os valores de estado e país.

In [288]:
if 'Pais' not in df_colunas_selecionadas:
  df_colunas_selecionadas.insert(3,'Pais','')
if 'Estado' not in df_colunas_selecionadas:
  df_colunas_selecionadas.insert(4,'Estado','')

Foi criada uma função que: 
1. Recebe o valor da coluna 'NATURAL'
2. Recorta todos os caracteres do inicio até o carecter anterior a penultima posição e o indentifica como o código do país.
3. Recorta os dois últimos números e os indentifica como o código do estado.
4. Usa o código do país como uma key no dicionário dict_pais e formata a exibição do value como uma string com a primeira letra em maiúscula e insere o nome de país no dataframe que está sendo analisada.
5. Faz o mesmo que o anterior, só que agora com os dados do estado.

In [289]:
def separar_natural():
  cod_natural = str(df_colunas_selecionadas['NATURAL'].values[index])
  cod_pais = str(cod_natural[:-2])
  cod_estado = str(cod_natural[-2:])
  df_colunas_selecionadas['Pais'].values[index] = str(dict_pais.get(cod_pais)).capitalize()
  df_colunas_selecionadas['Estado'].values[index] = dict_estado.get(cod_estado)

Cria um laço iterrante que aplica a função anterior a cada linha do dataframe.

In [290]:
for index,row in df_colunas_selecionadas.iterrows():
  separar_natural()
df_colunas_selecionadas.head()

  DF_ORIGEM Data de Obito  ... Municipio Natural Municipio Residência
0        ES    2020-05-08  ...    Afonso Cláudio            Cariacica
1        ES    2020-05-08  ...        Vila Velha              Vitória
2        ES    2020-05-12  ...               NaN           Vila Velha
3        ES    2020-03-07  ...      Baixo Guandu           Vila Velha
4        ES    2020-03-11  ...  Conselheiro Pena                Serra

[5 rows x 13 columns]

In [291]:
df_colunas_selecionadas = df_colunas_selecionadas[['DF_ORIGEM','Data de Obito', 'Pais','Estado', 'Data de Nascimento', 'SEXO', 'RACACOR', 'ASSISTMED', 'LINHAA', 'ESCFALAGR1', 'Municipio Natural','Municipio Residência']]
df_colunas_selecionadas

       DF_ORIGEM Data de Obito  ...  Municipio Natural Municipio Residência
0             ES    2020-05-08  ...     Afonso Cláudio            Cariacica
1             ES    2020-05-08  ...         Vila Velha              Vitória
2             ES    2020-05-12  ...                NaN           Vila Velha
3             ES    2020-03-07  ...       Baixo Guandu           Vila Velha
4             ES    2020-03-11  ...   Conselheiro Pena                Serra
...          ...           ...  ...                ...                  ...
701018        SP    2020-06-22  ...         Barro Alto            Săo Paulo
701019        SP    2020-04-23  ...             Lavras            Săo Paulo
701020        SP    2020-06-23  ...  Brasília de Minas            Săo Paulo
701021        SP    2020-06-23  ...         Mamanguape            Săo Paulo
701022        SP    2020-06-24  ...          Mairiporă            Săo Paulo

[701023 rows x 12 columns]

### Tratar coluna SEXO

In [292]:
if 'SEXO_2' not in df_colunas_selecionadas:
  df_colunas_selecionadas.insert(6,'SEXO_2','')

In [293]:
for index,row in df_colunas_selecionadas.iterrows():
  sexo = str(df_colunas_selecionadas['SEXO'].values[index])
  if sexo == '0':
    df_colunas_selecionadas['SEXO_2'].values[index] = 'Ignorado'
  elif sexo == '1':
    df_colunas_selecionadas['SEXO_2'].values[index] = 'Masculino'
  elif sexo == '2':
    df_colunas_selecionadas['SEXO_2'].values[index] = 'Feminino'
df_colunas_selecionadas

       DF_ORIGEM Data de Obito  ...  Municipio Natural Municipio Residência
0             ES    2020-05-08  ...     Afonso Cláudio            Cariacica
1             ES    2020-05-08  ...         Vila Velha              Vitória
2             ES    2020-05-12  ...                NaN           Vila Velha
3             ES    2020-03-07  ...       Baixo Guandu           Vila Velha
4             ES    2020-03-11  ...   Conselheiro Pena                Serra
...          ...           ...  ...                ...                  ...
701018        SP    2020-06-22  ...         Barro Alto            Săo Paulo
701019        SP    2020-04-23  ...             Lavras            Săo Paulo
701020        SP    2020-06-23  ...  Brasília de Minas            Săo Paulo
701021        SP    2020-06-23  ...         Mamanguape            Săo Paulo
701022        SP    2020-06-24  ...          Mairiporă            Săo Paulo

[701023 rows x 13 columns]

In [294]:
df_colunas_selecionadas = df_colunas_selecionadas[['DF_ORIGEM','Data de Obito', 'Pais','Estado', 'Data de Nascimento', 'SEXO_2', 'RACACOR', 'ASSISTMED', 'LINHAA', 'ESCFALAGR1', 'Municipio Natural','Municipio Residência']]
df_colunas_selecionadas.rename(columns={'SEXO_2': 'Sexo'}, inplace = True)
df_colunas_selecionadas

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

       DF_ORIGEM Data de Obito  ...  Municipio Natural Municipio Residência
0             ES    2020-05-08  ...     Afonso Cláudio            Cariacica
1             ES    2020-05-08  ...         Vila Velha              Vitória
2             ES    2020-05-12  ...                NaN           Vila Velha
3             ES    2020-03-07  ...       Baixo Guandu           Vila Velha
4             ES    2020-03-11  ...   Conselheiro Pena                Serra
...          ...           ...  ...                ...                  ...
701018        SP    2020-06-22  ...         Barro Alto            Săo Paulo
701019        SP    2020-04-23  ...             Lavras            Săo Paulo
701020        SP    2020-06-23  ...  Brasília de Minas            Săo Paulo
701021        SP    2020-06-23  ...         Mamanguape            Săo Paulo
701022        SP    2020-06-24  ...          Mairiporă            Săo Paulo

[701023 rows x 12 columns]

### Tratar coluna RACACOR

In [295]:
df_colunas_selecionadas

       DF_ORIGEM Data de Obito  ...  Municipio Natural Municipio Residência
0             ES    2020-05-08  ...     Afonso Cláudio            Cariacica
1             ES    2020-05-08  ...         Vila Velha              Vitória
2             ES    2020-05-12  ...                NaN           Vila Velha
3             ES    2020-03-07  ...       Baixo Guandu           Vila Velha
4             ES    2020-03-11  ...   Conselheiro Pena                Serra
...          ...           ...  ...                ...                  ...
701018        SP    2020-06-22  ...         Barro Alto            Săo Paulo
701019        SP    2020-04-23  ...             Lavras            Săo Paulo
701020        SP    2020-06-23  ...  Brasília de Minas            Săo Paulo
701021        SP    2020-06-23  ...         Mamanguape            Săo Paulo
701022        SP    2020-06-24  ...          Mairiporă            Săo Paulo

[701023 rows x 12 columns]

In [296]:
if 'RACACOR_2' not in df_colunas_selecionadas:
  df_colunas_selecionadas.insert(7,'RACACOR_2','')

In [297]:
df_colunas_selecionadas

       DF_ORIGEM Data de Obito  ...  Municipio Natural Municipio Residência
0             ES    2020-05-08  ...     Afonso Cláudio            Cariacica
1             ES    2020-05-08  ...         Vila Velha              Vitória
2             ES    2020-05-12  ...                NaN           Vila Velha
3             ES    2020-03-07  ...       Baixo Guandu           Vila Velha
4             ES    2020-03-11  ...   Conselheiro Pena                Serra
...          ...           ...  ...                ...                  ...
701018        SP    2020-06-22  ...         Barro Alto            Săo Paulo
701019        SP    2020-04-23  ...             Lavras            Săo Paulo
701020        SP    2020-06-23  ...  Brasília de Minas            Săo Paulo
701021        SP    2020-06-23  ...         Mamanguape            Săo Paulo
701022        SP    2020-06-24  ...          Mairiporă            Săo Paulo

[701023 rows x 13 columns]

In [298]:
for index,row in df_colunas_selecionadas.iterrows():
  raca = str(df_colunas_selecionadas['RACACOR'].values[index])
  if raca == '1':
    df_colunas_selecionadas['RACACOR_2'].values[index] = 'Branca'
  elif raca == '2':
    df_colunas_selecionadas['RACACOR_2'].values[index] = 'Preta'
  elif raca == '3':
    df_colunas_selecionadas['RACACOR_2'].values[index] = 'Amarela'
  elif raca == '4':
    df_colunas_selecionadas['RACACOR_2'].values[index] = 'Parda'
  elif raca == '5':
    df_colunas_selecionadas['RACACOR_2'].values[index] = 'Indígena'
df_colunas_selecionadas

       DF_ORIGEM Data de Obito  ...  Municipio Natural Municipio Residência
0             ES    2020-05-08  ...     Afonso Cláudio            Cariacica
1             ES    2020-05-08  ...         Vila Velha              Vitória
2             ES    2020-05-12  ...                NaN           Vila Velha
3             ES    2020-03-07  ...       Baixo Guandu           Vila Velha
4             ES    2020-03-11  ...   Conselheiro Pena                Serra
...          ...           ...  ...                ...                  ...
701018        SP    2020-06-22  ...         Barro Alto            Săo Paulo
701019        SP    2020-04-23  ...             Lavras            Săo Paulo
701020        SP    2020-06-23  ...  Brasília de Minas            Săo Paulo
701021        SP    2020-06-23  ...         Mamanguape            Săo Paulo
701022        SP    2020-06-24  ...          Mairiporă            Săo Paulo

[701023 rows x 13 columns]

In [299]:
df_colunas_selecionadas = df_colunas_selecionadas[['DF_ORIGEM','Data de Obito', 'Pais','Estado', 'Data de Nascimento', 'Sexo', 'RACACOR_2', 'ASSISTMED', 'LINHAA', 'ESCFALAGR1', 'Municipio Natural','Municipio Residência']]
df_colunas_selecionadas.rename(columns={'RACACOR_2': 'Raça'}, inplace = True)
df_colunas_selecionadas

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

       DF_ORIGEM Data de Obito  ...  Municipio Natural Municipio Residência
0             ES    2020-05-08  ...     Afonso Cláudio            Cariacica
1             ES    2020-05-08  ...         Vila Velha              Vitória
2             ES    2020-05-12  ...                NaN           Vila Velha
3             ES    2020-03-07  ...       Baixo Guandu           Vila Velha
4             ES    2020-03-11  ...   Conselheiro Pena                Serra
...          ...           ...  ...                ...                  ...
701018        SP    2020-06-22  ...         Barro Alto            Săo Paulo
701019        SP    2020-04-23  ...             Lavras            Săo Paulo
701020        SP    2020-06-23  ...  Brasília de Minas            Săo Paulo
701021        SP    2020-06-23  ...         Mamanguape            Săo Paulo
701022        SP    2020-06-24  ...          Mairiporă            Săo Paulo

[701023 rows x 12 columns]

### Tratar coluna ASSISTMED

In [300]:
df_colunas_selecionadas

       DF_ORIGEM Data de Obito  ...  Municipio Natural Municipio Residência
0             ES    2020-05-08  ...     Afonso Cláudio            Cariacica
1             ES    2020-05-08  ...         Vila Velha              Vitória
2             ES    2020-05-12  ...                NaN           Vila Velha
3             ES    2020-03-07  ...       Baixo Guandu           Vila Velha
4             ES    2020-03-11  ...   Conselheiro Pena                Serra
...          ...           ...  ...                ...                  ...
701018        SP    2020-06-22  ...         Barro Alto            Săo Paulo
701019        SP    2020-04-23  ...             Lavras            Săo Paulo
701020        SP    2020-06-23  ...  Brasília de Minas            Săo Paulo
701021        SP    2020-06-23  ...         Mamanguape            Săo Paulo
701022        SP    2020-06-24  ...          Mairiporă            Săo Paulo

[701023 rows x 12 columns]

In [301]:
if 'ASSISTMED_2' not in df_colunas_selecionadas:
  df_colunas_selecionadas.insert(8,'ASSISTMED_2','')

In [302]:
df_colunas_selecionadas

       DF_ORIGEM Data de Obito  ...  Municipio Natural Municipio Residência
0             ES    2020-05-08  ...     Afonso Cláudio            Cariacica
1             ES    2020-05-08  ...         Vila Velha              Vitória
2             ES    2020-05-12  ...                NaN           Vila Velha
3             ES    2020-03-07  ...       Baixo Guandu           Vila Velha
4             ES    2020-03-11  ...   Conselheiro Pena                Serra
...          ...           ...  ...                ...                  ...
701018        SP    2020-06-22  ...         Barro Alto            Săo Paulo
701019        SP    2020-04-23  ...             Lavras            Săo Paulo
701020        SP    2020-06-23  ...  Brasília de Minas            Săo Paulo
701021        SP    2020-06-23  ...         Mamanguape            Săo Paulo
701022        SP    2020-06-24  ...          Mairiporă            Săo Paulo

[701023 rows x 13 columns]

In [303]:
for index,row in df_colunas_selecionadas.iterrows():
  assistencia = str(df_colunas_selecionadas['ASSISTMED'].values[index])
  if assistencia == '9':
    df_colunas_selecionadas['ASSISTMED_2'].values[index] = 'Ignorado'
  elif assistencia == '1':
    df_colunas_selecionadas['ASSISTMED_2'].values[index] = 'Com assistência'
  elif assistencia == '2':
    df_colunas_selecionadas['ASSISTMED_2'].values[index] = 'Sem assistência'
df_colunas_selecionadas

       DF_ORIGEM Data de Obito  ...  Municipio Natural Municipio Residência
0             ES    2020-05-08  ...     Afonso Cláudio            Cariacica
1             ES    2020-05-08  ...         Vila Velha              Vitória
2             ES    2020-05-12  ...                NaN           Vila Velha
3             ES    2020-03-07  ...       Baixo Guandu           Vila Velha
4             ES    2020-03-11  ...   Conselheiro Pena                Serra
...          ...           ...  ...                ...                  ...
701018        SP    2020-06-22  ...         Barro Alto            Săo Paulo
701019        SP    2020-04-23  ...             Lavras            Săo Paulo
701020        SP    2020-06-23  ...  Brasília de Minas            Săo Paulo
701021        SP    2020-06-23  ...         Mamanguape            Săo Paulo
701022        SP    2020-06-24  ...          Mairiporă            Săo Paulo

[701023 rows x 13 columns]

In [304]:
df_colunas_selecionadas = df_colunas_selecionadas[['DF_ORIGEM','Data de Obito', 'Pais','Estado', 'Data de Nascimento', 'Sexo', 'Raça', 'ASSISTMED_2', 'LINHAA', 'ESCFALAGR1', 'Municipio Natural','Municipio Residência']]
df_colunas_selecionadas.rename(columns={'ASSISTMED_2': 'Teve assistência?'}, inplace = True)
df_colunas_selecionadas

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

       DF_ORIGEM Data de Obito  ...  Municipio Natural Municipio Residência
0             ES    2020-05-08  ...     Afonso Cláudio            Cariacica
1             ES    2020-05-08  ...         Vila Velha              Vitória
2             ES    2020-05-12  ...                NaN           Vila Velha
3             ES    2020-03-07  ...       Baixo Guandu           Vila Velha
4             ES    2020-03-11  ...   Conselheiro Pena                Serra
...          ...           ...  ...                ...                  ...
701018        SP    2020-06-22  ...         Barro Alto            Săo Paulo
701019        SP    2020-04-23  ...             Lavras            Săo Paulo
701020        SP    2020-06-23  ...  Brasília de Minas            Săo Paulo
701021        SP    2020-06-23  ...         Mamanguape            Săo Paulo
701022        SP    2020-06-24  ...          Mairiporă            Săo Paulo

[701023 rows x 12 columns]

### Tratar ESCFALAGR1

In [305]:
df_colunas_selecionadas = df_colunas_selecionadas.merge(df_escolaridade,how='left', left_on='ESCFALAGR1', right_on='codigo')
df_colunas_selecionadas = df_colunas_selecionadas[['DF_ORIGEM','Data de Obito','Pais', 'Estado', 'Data de Nascimento', 'Sexo', 'Raça', 'Teve assistência?', 'LINHAA', 'Municipio Natural','Municipio Residência', 'nivel']]
df_colunas_selecionadas.rename(columns={'nivel': 'Formação'}, inplace = True)
df_colunas_selecionadas

       DF_ORIGEM  ...                                   Formação
0             ES  ...                                        NaN
1             ES  ...                          Superior Completo
2             ES  ...                                   Ignorado
3             ES  ...                                   Ignorado
4             ES  ...  Fundamental II Incompleto ou Inespecífico
...          ...  ...                                        ...
701018        SP  ...                                   Ignorado
701019        SP  ...   Fundamental I Incompleto ou Inespecífico
701020        SP  ...   Fundamental I Incompleto ou Inespecífico
701021        SP  ...   Fundamental I Incompleto ou Inespecífico
701022        SP  ...   Fundamental I Incompleto ou Inespecífico

[701023 rows x 12 columns]

### Tratar coluna LINHAA

In [306]:
if 'LINHAA_2' not in df_colunas_selecionadas:
  df_colunas_selecionadas.insert(9,'LINHAA_2','')

In [307]:
for index,row in df_colunas_selecionadas.iterrows():
  cid = str(df_colunas_selecionadas['LINHAA'].values[index])
  cid = str(cid[1:5])
  df_colunas_selecionadas['LINHAA_2'].values[index] = cid
df_colunas_selecionadas

       DF_ORIGEM  ...                                   Formação
0             ES  ...                                        NaN
1             ES  ...                          Superior Completo
2             ES  ...                                   Ignorado
3             ES  ...                                   Ignorado
4             ES  ...  Fundamental II Incompleto ou Inespecífico
...          ...  ...                                        ...
701018        SP  ...                                   Ignorado
701019        SP  ...   Fundamental I Incompleto ou Inespecífico
701020        SP  ...   Fundamental I Incompleto ou Inespecífico
701021        SP  ...   Fundamental I Incompleto ou Inespecífico
701022        SP  ...   Fundamental I Incompleto ou Inespecífico

[701023 rows x 13 columns]

In [308]:
df_colunas_selecionadas = df_colunas_selecionadas[['DF_ORIGEM','Data de Obito','Pais', 'Estado', 'Data de Nascimento', 'Sexo', 'Raça', 'Teve assistência?', 'LINHAA_2', 'Municipio Natural','Municipio Residência', 'Formação']]
df_colunas_selecionadas.rename(columns={'LINHAA_2': 'Cod. Causa da Morte'}, inplace = True)
df_colunas_selecionadas

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

       DF_ORIGEM  ...                                   Formação
0             ES  ...                                        NaN
1             ES  ...                          Superior Completo
2             ES  ...                                   Ignorado
3             ES  ...                                   Ignorado
4             ES  ...  Fundamental II Incompleto ou Inespecífico
...          ...  ...                                        ...
701018        SP  ...                                   Ignorado
701019        SP  ...   Fundamental I Incompleto ou Inespecífico
701020        SP  ...   Fundamental I Incompleto ou Inespecífico
701021        SP  ...   Fundamental I Incompleto ou Inespecífico
701022        SP  ...   Fundamental I Incompleto ou Inespecífico

[701023 rows x 12 columns]

### Pegando a descrição da Causa da Morte

In [309]:
df_colunas_selecionadas.head()

  DF_ORIGEM  ...                                   Formação
0        ES  ...                                        NaN
1        ES  ...                          Superior Completo
2        ES  ...                                   Ignorado
3        ES  ...                                   Ignorado
4        ES  ...  Fundamental II Incompleto ou Inespecífico

[5 rows x 12 columns]

In [310]:
df_colunas_selecionadas = df_colunas_selecionadas.merge(df_causa_morte, how='left', left_on='Cod. Causa da Morte', right_on='CID10')

In [311]:
df_colunas_selecionadas = df_colunas_selecionadas[['DF_ORIGEM','Data de Obito','Pais', 'Estado', 'Data de Nascimento', 'Sexo', 'Raça', 'Teve assistência?', 'Cod. Causa da Morte', 'Municipio Natural','Municipio Residência', 'Formação','DESCR']]
df_colunas_selecionadas.rename(columns={'DESCR': 'Descrição da Causa Morte'}, inplace = True)
df_colunas_selecionadas

       DF_ORIGEM  ...                     Descrição da Causa Morte
0             ES  ...  K55.0 Transt vasculares agudos do intestino
1             ES  ...                             Y00.0 Residencia
2             ES  ...      G93.2 Hipertensao intracraniana benigna
3             ES  ...                    I63.9 Infarto cerebral NE
4             ES  ...               I67.9 Doenc cerebrovascular NE
...          ...  ...                                          ...
701018        SP  ...             J98.8 Outr transt respirat espec
701019        SP  ...                      J96.9 Insuf respirat NE
701020        SP  ...             J98.8 Outr transt respirat espec
701021        SP  ...             J98.8 Outr transt respirat espec
701022        SP  ...             J98.8 Outr transt respirat espec

[701023 rows x 13 columns]

### Tratando o texto da descrição da causa morte

In [312]:
if 'Descrição da Causa Morte_2' not in df_colunas_selecionadas:
  df_colunas_selecionadas.insert(13,'Descrição da Causa Morte_2','')

In [313]:
for index,row in df_colunas_selecionadas.iterrows():
  cid = str(df_colunas_selecionadas['Descrição da Causa Morte'].values[index])
  cid = str(cid[6:])
  df_colunas_selecionadas['Descrição da Causa Morte_2'].values[index] = cid
df_colunas_selecionadas

       DF_ORIGEM  ...             Descrição da Causa Morte_2
0             ES  ...  Transt vasculares agudos do intestino
1             ES  ...                             Residencia
2             ES  ...      Hipertensao intracraniana benigna
3             ES  ...                    Infarto cerebral NE
4             ES  ...               Doenc cerebrovascular NE
...          ...  ...                                    ...
701018        SP  ...             Outr transt respirat espec
701019        SP  ...                      Insuf respirat NE
701020        SP  ...             Outr transt respirat espec
701021        SP  ...             Outr transt respirat espec
701022        SP  ...             Outr transt respirat espec

[701023 rows x 14 columns]

In [314]:
df_colunas_selecionadas = df_colunas_selecionadas[['DF_ORIGEM','Data de Obito','Pais', 'Estado', 'Data de Nascimento', 'Sexo', 'Raça', 'Teve assistência?', 'Cod. Causa da Morte', 'Municipio Natural','Municipio Residência', 'Formação', 'Descrição da Causa Morte_2']]
df_colunas_selecionadas.rename(columns={'Descrição da Causa Morte_2': 'Descrição da Causa Morte'}, inplace = True)
df_colunas_selecionadas

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

       DF_ORIGEM  ...               Descrição da Causa Morte
0             ES  ...  Transt vasculares agudos do intestino
1             ES  ...                             Residencia
2             ES  ...      Hipertensao intracraniana benigna
3             ES  ...                    Infarto cerebral NE
4             ES  ...               Doenc cerebrovascular NE
...          ...  ...                                    ...
701018        SP  ...             Outr transt respirat espec
701019        SP  ...                      Insuf respirat NE
701020        SP  ...             Outr transt respirat espec
701021        SP  ...             Outr transt respirat espec
701022        SP  ...             Outr transt respirat espec

[701023 rows x 13 columns]

### Reordenando as colunas

In [315]:
df_colunas_selecionadas = df_colunas_selecionadas[['Data de Obito','Data de Nascimento','Pais', 'Estado','Municipio Natural','Municipio Residência', 'Sexo', 'Raça','Formação', 'Cod. Causa da Morte', 'Descrição da Causa Morte', 'Teve assistência?', 'DF_ORIGEM',]]
df_colunas_selecionadas

       Data de Obito Data de Nascimento  ... Teve assistência? DF_ORIGEM
0         2020-05-08         1976-06-25  ...   Com assistência        ES
1         2020-05-08         1980-08-13  ...   Sem assistência        ES
2         2020-05-12         1970-07-22  ...   Com assistência        ES
3         2020-03-07         1945-01-18  ...   Com assistência        ES
4         2020-03-11         1938-07-05  ...   Com assistência        ES
...              ...                ...  ...               ...       ...
701018    2020-06-22         1941-12-15  ...                          SP
701019    2020-04-23         1955-08-12  ...   Com assistência        SP
701020    2020-06-23         1965-12-12  ...   Com assistência        SP
701021    2020-06-23         1935-08-08  ...   Com assistência        SP
701022    2020-06-24         1938-08-15  ...   Com assistência        SP

[701023 rows x 13 columns]

### Filtrando somente as linhas com as causas mortes seleciondas

In [316]:
septicemia = 'Septicemia NE'
insuficiencia = 'Insuf respirat aguda'
coronavirus = 'Infecc p/coronavirus NE'
parada = 'Parada respirat'
choque = 'Choque cardiogenico'

In [317]:
df_septicemia = df_colunas_selecionadas.loc[df_colunas_selecionadas['Descrição da Causa Morte'] == septicemia]
df_septicemia

       Data de Obito Data de Nascimento  ... Teve assistência? DF_ORIGEM
8         2020-03-15         1948-02-21  ...   Com assistência        ES
11        2020-03-23         1957-11-27  ...   Com assistência        ES
15        2020-03-31         1965-06-25  ...   Com assistência        ES
20        2020-05-29         1966-06-03  ...   Com assistência        ES
28        2020-05-31         1951-05-10  ...   Com assistência        ES
...              ...                ...  ...               ...       ...
700997    2020-06-23         1949-03-06  ...                          SP
700999    2020-06-24         1948-01-18  ...   Com assistência        SP
701000    2020-06-23         1975-03-17  ...   Com assistência        SP
701001    2020-06-22         1933-08-30  ...                          SP
701006    2020-06-23         1968-09-17  ...                          SP

[107405 rows x 13 columns]

In [318]:
df_insuficiencia = df_colunas_selecionadas.loc[df_colunas_selecionadas['Descrição da Causa Morte'] == insuficiencia]
df_insuficiencia

       Data de Obito Data de Nascimento  ... Teve assistência? DF_ORIGEM
51        2020-06-14         1985-05-14  ...   Com assistência        ES
56        2020-06-17         1967-11-02  ...   Com assistência        ES
60        2020-06-23         1935-09-09  ...   Com assistência        ES
66        2020-06-29         1934-01-10  ...   Com assistência        ES
67        2020-06-29         1948-11-16  ...   Com assistência        ES
...              ...                ...  ...               ...       ...
700961    2020-06-16         1925-11-19  ...   Com assistência        SP
700980    2020-06-20         1951-01-15  ...   Com assistência        SP
700984    2020-06-22         1959-01-14  ...   Com assistência        SP
700991    2020-06-18         1942-02-09  ...   Com assistência        SP
701011    2020-01-27         1945-05-06  ...   Com assistência        SP

[58482 rows x 13 columns]

In [319]:
df_coronavirus = df_colunas_selecionadas.loc[df_colunas_selecionadas['Descrição da Causa Morte'] == coronavirus]
df_coronavirus

       Data de Obito Data de Nascimento  ... Teve assistência? DF_ORIGEM
221       2020-04-10         1958-07-06  ...   Com assistência        ES
228       2020-04-12         1940-02-12  ...   Com assistência        ES
299       2020-05-29         1944-08-08  ...   Com assistência        ES
361       2020-05-23         1936-12-12  ...   Com assistência        ES
364       2020-05-19         1979-12-30  ...   Com assistência        ES
...              ...                ...  ...               ...       ...
700707    2020-12-08         1957-11-29  ...   Com assistência        SP
700825    2020-12-20         1935-04-10  ...   Com assistência        SP
700931    2020-06-22         1948-11-24  ...   Com assistência        SP
701004    2020-06-24         1950-03-03  ...   Com assistência        SP
701005    2020-06-24         1951-06-13  ...   Com assistência        SP

[21311 rows x 13 columns]

In [320]:
df_parada = df_colunas_selecionadas.loc[df_colunas_selecionadas['Descrição da Causa Morte'] == parada]
df_parada

       Data de Obito Data de Nascimento  ... Teve assistência? DF_ORIGEM
48        2020-06-15         1968-05-23  ...   Com assistência        ES
49        2020-06-02         1975-06-12  ...   Com assistência        ES
68        2020-06-28         1924-07-21  ...   Com assistência        ES
69        2020-06-28         1970-07-29  ...   Com assistência        ES
119       2020-06-01         1934-02-15  ...   Com assistência        ES
...              ...                ...  ...               ...       ...
700772    2020-11-21         1954-05-29  ...   Sem assistência        SP
700834    2020-11-02         1921-10-30  ...          Ignorado        SP
700897    2020-12-05         1941-03-26  ...   Com assistência        SP
700918    2020-05-09         1984-10-02  ...   Com assistência        SP
700934    2020-06-17         1971-10-13  ...   Com assistência        SP

[24366 rows x 13 columns]

In [321]:
df_choque = df_colunas_selecionadas.loc[df_colunas_selecionadas['Descrição da Causa Morte'] == choque]
df_choque

       Data de Obito Data de Nascimento  ... Teve assistência? DF_ORIGEM
40        2020-05-30         1948-11-30  ...   Com assistência        ES
44        2020-06-01         1958-04-19  ...   Com assistência        ES
59        2020-06-23         1958-06-06  ...   Com assistência        ES
61        2020-05-27         1966-04-01  ...   Com assistência        ES
80        2020-03-20         1960-11-09  ...   Sem assistência        ES
...              ...                ...  ...               ...       ...
700847    2020-11-12         1951-12-22  ...   Com assistência        SP
700850    2020-11-12         1968-03-19  ...   Com assistência        SP
700928    2020-05-24         1959-10-08  ...   Com assistência        SP
700942    2020-06-19         1948-01-05  ...   Com assistência        SP
701010    2020-05-11         1943-03-15  ...   Com assistência        SP

[31883 rows x 13 columns]

In [322]:
df_final = pd.concat([df_septicemia, df_insuficiencia, df_coronavirus, df_parada, df_choque])
df_final

       Data de Obito Data de Nascimento  ... Teve assistência? DF_ORIGEM
8         2020-03-15         1948-02-21  ...   Com assistência        ES
11        2020-03-23         1957-11-27  ...   Com assistência        ES
15        2020-03-31         1965-06-25  ...   Com assistência        ES
20        2020-05-29         1966-06-03  ...   Com assistência        ES
28        2020-05-31         1951-05-10  ...   Com assistência        ES
...              ...                ...  ...               ...       ...
700847    2020-11-12         1951-12-22  ...   Com assistência        SP
700850    2020-11-12         1968-03-19  ...   Com assistência        SP
700928    2020-05-24         1959-10-08  ...   Com assistência        SP
700942    2020-06-19         1948-01-05  ...   Com assistência        SP
701010    2020-05-11         1943-03-15  ...   Com assistência        SP

[243447 rows x 13 columns]

### Extraindo o dataframe final

In [323]:
df_final.to_csv('/content/drive/MyDrive/dados/Projeto Integrador VI/sim-tratado.csv')

## Análise de Qualidade

In [324]:
df_final.head()

   Data de Obito Data de Nascimento  ... Teve assistência? DF_ORIGEM
8     2020-03-15         1948-02-21  ...   Com assistência        ES
11    2020-03-23         1957-11-27  ...   Com assistência        ES
15    2020-03-31         1965-06-25  ...   Com assistência        ES
20    2020-05-29         1966-06-03  ...   Com assistência        ES
28    2020-05-31         1951-05-10  ...   Com assistência        ES

[5 rows x 13 columns]

### Criando as funções que calcula o NAN e o NULL

In [325]:
def quantidade_nan(coluna):
  quantidade_linhas = len(df_final)
  quantidade_de_nan = df_final[coluna].isna().sum()
  porcentagem_nan =  quantidade_de_nan * 100 / quantidade_linhas
  return format(porcentagem_nan, '.2f')

In [326]:
def quantidade_null(coluna):
  quantidade_linhas = len(df_final)
  quantidade_de_null = df_final[coluna].isnull().sum()
  porcentagem_null =  quantidade_de_null * 100 / quantidade_linhas
  return format(porcentagem_null, '.2f')

In [327]:
def quantidade_vazios(coluna):
  tabela = df_final.loc[df_final[coluna] == '']
  quantidade_vazios = len(tabela)
  quantidade_linhas = len(df_final)
  porcentagem_vazios =  quantidade_vazios * 100 / quantidade_linhas
  return format(porcentagem_vazios, '.2f')

### Qualidade da coluna 'Data de Obito'

In [328]:
nan_data_obito = quantidade_nan('Data de Obito')
nan_data_obito

'0.00'

In [329]:
null_data_obito = quantidade_null('Data de Obito')
null_data_obito

'0.00'

In [330]:
vazios_data_obito = quantidade_vazios('Data de Obito')
vazios_data_obito

'0.00'

### Qualidade da coluna 'Data de Nascimento'

In [331]:
nan_data_nascimento = quantidade_nan('Data de Nascimento')
nan_data_nascimento

'0.06'

In [332]:
null_data_obito = quantidade_null('Data de Nascimento')
null_data_obito

'0.06'

### Qualidade da coluna 'Pais'

In [333]:
nan_pais = quantidade_nan('Pais')
nan_pais

'0.00'

In [334]:
null_pais = quantidade_null('Pais')
null_pais

'0.00'

### Qualidade da coluna 'Estado'

In [335]:
nan_estado = quantidade_nan('Estado')
nan_estado

'10.37'

In [336]:
null_estado = quantidade_null('Estado')
null_estado

'10.37'

### Qualidade da coluna 'Municipio Natural'

In [337]:
nan_municipio_natural = quantidade_nan('Municipio Natural')
nan_municipio_natural

'10.96'

In [338]:
null_municipio_natural = quantidade_null('Municipio Natural')
null_municipio_natural

'10.96'

### Qualidade da coluna 'Municipio Residência'

In [339]:
nan_municipio_residencia = quantidade_nan('Municipio Residência')
nan_municipio_residencia

'0.00'

In [340]:
null_municipio_residencia = quantidade_null('Municipio Residência')
null_municipio_residencia

'0.00'

### Qualidade da coluna 'Sexo'

In [341]:
nan_sexo = quantidade_nan('Sexo')
nan_sexo

'0.00'

In [342]:
null_sexo = quantidade_null('Sexo')
null_sexo

'0.00'

### Qualidade da coluna 'Raça'

In [343]:
nan_raca = quantidade_nan('Raça')
nan_raca

'0.00'

In [344]:
null_raca = quantidade_null('Raça')
null_raca

'0.00'

In [345]:
vazios_raca = quantidade_vazios('Raça')
vazios_raca

'2.11'

### Qualidade da coluna 'Formação'

In [346]:
nan_formacao = quantidade_nan('Formação')
nan_formacao

'4.86'

In [347]:
null_formacao = quantidade_null('Formação')
null_formacao

'4.86'

### Qualidade da coluna 'Cod. Causa da Morte'

In [348]:
nan_cod_morte = quantidade_nan('Cod. Causa da Morte')
nan_cod_morte

'0.00'

In [349]:
null_cod_morte = quantidade_null('Cod. Causa da Morte')
null_cod_morte

'0.00'

### Qualidade da coluna 'Descrição da Causa Morte'

In [350]:
nan_des_morte = quantidade_nan('Descrição da Causa Morte')
nan_des_morte

'0.00'

In [351]:
null_des_morte = quantidade_null('Descrição da Causa Morte')
null_des_morte

'0.00'

### Qualidade da coluna 'Teve assistência?'

In [352]:
nan_assistencia = quantidade_nan('Teve assistência?')
nan_assistencia

'0.00'

In [353]:
null_assistencia = quantidade_null('Teve assistência?')
null_assistencia

'0.00'

### Qualidade da coluna 'DF_ORIGEM'

In [354]:
nan_origem = quantidade_nan('DF_ORIGEM')
nan_origem

'0.00'

In [355]:
null_origem = quantidade_null('DF_ORIGEM')
null_origem

'0.00'